### ISSUE TITLE
Support osx-arm64

### ISSUE THREAD

**Issue by mrocklin** [conda-forge/deltalake-feedstock#24]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I tried installing this on my macbook and was sad that it wasn't found.  I suspect that this was due to there not being an osx-arm64 build (but I don't know much about packaging for the M1).  

### Installed packages

```shell
This was done from a fresh environment
```

### Environment info

```shell
active environment : coiled-docs
    active env location : /Users/mrocklin/mambaforge/envs/coiled-docs
            shell level : 2
       user config file : /Users/mrocklin/.condarc
 populated config files : /Users/mrocklin/mambaforge/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.6.2=0
                          __unix=0=0
       base environment : /Users/mrocklin/mambaforge  (writable)
      conda av data dir : /Users/mrocklin/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/mrocklin/mambaforge/pkgs
                          /Users/mrocklin/.conda/pkgs
       envs directories : /Users/mrocklin/mambaforge/envs
                          /Users/mrocklin/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.3.1 requests/2.29.0 CPython/3.9.16 Darwin/22.6.0 OSX/13.6.2
                UID:GID : 502:20
             netrc file : /Users/mrocklin/.netrc
           offline mode : False
```

**Comment by jakirkham** [comment]
Please submit a PR adding it to [this list]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt )

For an example, please see this PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5473

**Comment by mrocklin** [comment]
@jakirkham is there a similar procedure for `linux-aarch64`?  Also, if you have time to put on your PyData hat, are there other targets that one should also think about generally for projects like this?

**Comment by jakirkham** [comment]
There is the [arch migration list]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt )

Same procedure as before

Nothing else that I can think of

**Comment by mrocklin** [comment]
Cool.  Maybe this is it then: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5582
