### ISSUE TITLE
Fix ppc64le builds

### ISSUE THREAD

**Issue by charlesbluca** [conda-forge/deltalake-feedstock#44]
### Comment:

As of v0.18.1, linux-ppc64le builds have been failing:

https://github.com/conda-forge/deltalake-feedstock/pull/42#issuecomment-2164073936

Seems like this error is around linking the openssl Rust dependency, but haven't had the capacity to look into this deeper and otherwise would like this not to be a release blocker in the meantime

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render
